name: gf_app
description: A GetWidget Demo App

version: 1.0.8+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # getwidget: ^1.1.3
  getwidget:
    git: https://github.com/MrHallows/getwidget.git
    # path: ../getwidget
  flutter_webview_plugin: ^0.3.11
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/image.png
    - assets/images/image1.png
    - assets/images/red.png
    - assets/images/purple.png
    - assets/images/pink.png
    - assets/images/orange.png
    - assets/images/image2.png
    - assets/images/img.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/card.png
    - assets/images/card1.png
    - assets/images/card2.png
    - assets/images/card3.png
    - assets/images/card5.png
    - assets/images/card4.png
    - assets/images/gflogo.png
    - assets/images/avatar1.png
    - assets/images/avatar2.png
    - assets/images/avatar3.png
    - assets/images/avatar4.png
    - assets/images/avatar5.png
    - assets/images/avatar6.png
    - assets/images/avatar7.png
    - assets/images/avatar8.png
    - assets/images/avatar9.png
    - assets/images/avatar10.png
    - assets/images/avatar11.png
    - assets/images/avatar12.png
    - assets/gif/success1.gif
    - assets/icons/gflogo.png

  fonts:
    # Text Fonts
    - family: Maven Pro
      fonts:
        - asset: assets/fonts/MavenPro-Black.ttf
          weight: 900
        - asset: assets/fonts/MavenPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MavenPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/MavenPro-Regular.ttf
          weight: 400

    # Icon Fonts
    - family: GFFontIcons
      fonts:
        - asset: assets/fonts/gfFontIcon.ttf
          weight: 400
    - family: GFFontIcons2
      fonts:
        - asset: assets/fonts/gfFontIcons2.ttf
          weight: 400
    - family: GFSocialFonts
      fonts:
        - asset: assets/fonts/gfSocialFonts.ttf
          weight: 400
    - family: GFIconFonts
      fonts:
        - asset: assets/fonts/gfIconFonts.ttf
          weight: 400
    - family: GFIcons
      fonts:
        - asset: assets/fonts/loader.ttf
          weight: 400
